### ISSUE TITLE
Brackets aren't correctly registered under Windows 8 on a Spanish keyboard layout

### ISSUE THREAD

**Issue by modulux** [trptcolin/reply#156]
On version 0.3.0 entering brackets ([]) works perfectly fine, but on 0.3.5 open bracket ([) doesn't register as a key, nor does ]. This is under Windows 8 cmd.exe, Spanish keyboard layout, using lein repl.

**Comment by hyPiRion** [comment]
According to a comment in technomancy/leiningen#1636, this should've been resolved with jline 2.12.1.

**Comment by winks** [comment]
Verified that it fixes [technomancy/leiningen#1636](https://github.com/technomancy/leiningen/issues/1636) - we just need a new reply release with jline 2.12.1 in it.

Only tested on Windows 7 but looking at the bug in the jline/reply/leiningen/scala bugtracker that doesn't seem to matter between tested windows versions.
