### ISSUE TITLE
nrepl server listens on 0.0.0.0 by default

### ISSUE THREAD

**Issue by emidln** [trptcolin/reply#160]
I know this is a transitive issue from tools.nrepl, but as an end-user tool (an improved clojure.main experience), REPL-y shouldn't open a port to the outside world by default. Relevant code is at https://github.com/trptcolin/reply/blob/master/src/clj/reply/eval_modes/nrepl.clj#L155. 

This is actually handled downstream for some (most?) users since leiningen defaults to 127.0.0.1. This should be REPLy's default as well.

**Comment by technomancy** [comment]
I think this can be closed now; it looks like `host` defaults to `"localhost"`: https://github.com/trptcolin/reply/blob/master/src/clj/reply/eval_modes/nrepl.clj#L146

**Comment by bbatsov** [comment]
Yeah, this can be closed.
