### ISSUE TITLE
0.3.6 pom marks tools.nrepl dep as scope "test"

### ISSUE THREAD

**Issue by alandipert** [trptcolin/reply#162]
Over at https://github.com/boot-clj/boot/pull/168 @bbatsov bumped our reply dependency to 0.3.6 but it  broke our build.  We got an error during AOT that tools.nrepl was missing.

We tracked the problem down to the fact that the reply pom as found on Clojars [depends on tools.nrepl but with "test" scope](https://gist.github.com/alandipert/1331e5aa8c6f2f17678e#file-pom-xml-L99-L110).  This prevents consumers of reply from downloading tools.nrepl as a transitive dependency.

We think this is probably caused by a lein bug, https://github.com/technomancy/leiningen/issues/1748.  You might be able to fix it by deploying with a different version of lein.

Anyway, thanks in advance for looking into it!  For anyone else with this problem, one workaround is to depend on `[org.clojure/tools.nrepl "0.2.8"]` in addition to `[reply "0.3.6"]`.

**Comment by trptcolin** [comment]
Ah, yuck, thanks for the detective work! I went ahead and released `[reply "0.3.7"]` with @jcrossley3's workaround linked from technomancy/leiningen#1771

I guess I probably could've re-deployed 0.3.6 with an older version of lein, but figured I'd do a new one on the off-chance someone is relying on that [afaict wrong] behavior.

**Comment by alandipert** [comment]
:metal: :dolphin: :metal:
