### ISSUE TITLE
Allow setting max history size

### ISSUE THREAD

**Issue by timmc** [trptcolin/reply#166]
Currently jline [defaults](https://github.com/jline/jline2/blob/6b1074908f4001026ba923ed64960d9f6c7491ec/src/main/java/jline/console/history/MemoryHistory.java#L28) to a max history size of 500, which is pretty tiny. I often want to recall expressions from thousands or tens of thousands of lines back in `lein repl`.

Ideally jline would just pick up the .inputrc settings; I've filed https://github.com/jline/jline2/issues/277 to see if they'd take a PR on that.

I'd also be up for submitting a PR here to configure jline more explicitly from a new `:repl-options` key, but I'm not sure how that would interact with jline vs. rlwrap.

**Comment by timmc** [comment]
Oh hmm!

> JLine 2.x development has come to an end, and users are encouraged to investigate the use of JLine 3.x instead.

**Comment by timmc-bcov** [comment]
Addressed by https://github.com/trptcolin/reply/pull/183
