### ISSUE TITLE
Move to compliment

### ISSUE THREAD

**Issue by tirkarthi** [trptcolin/reply#176]
clojure-complete is not being actively maintained and has a bug that causes NPE in JDK. It has been fixed upstream but not released. I think it will be good if reply migrates to use [compliment](https://github.com/alexander-yakushev/compliment) which is actively maintained.

JDK 9 issue in clojure-complete : https://github.com/ninjudd/clojure-complete/issues/24

**Comment by trptcolin** [comment]
Compliment is indeed cool. If somebody wants to work out a fix for the issues in  https://github.com/trptcolin/reply/pull/153 I'm happy to test it out. I'm not going to do this work myself though, as I don't have any current pain with clojure-complete. I've just released clojure-complete 0.2.5 which includes the very recent jdk9 fix.
