### ISSUE TITLE
Bump nrepl version

### ISSUE THREAD

**Issue by mlococo** [trptcolin/reply#180]
Recent versions of cider require nrepl 0.2.12 or greater to function properly. While reply users can deal with this locally through exclusions and explicit version deps on nrepl, it would be nice to default to a recent nrepl to maximize compatibility with other common tools.

**Comment by trptcolin** [comment]
Bumped to 0.2.13 of the contrib nREPL on master; will move to the nrepl-org one eventually, yep.
