### ISSUE TITLE
Migration plans for nREPL 0.4+

### ISSUE THREAD

**Issue by bbatsov** [trptcolin/reply#181]
That's basically a follow up of https://github.com/nrepl/nREPL/issues/1 and was also discussed in https://github.com/nrepl/nREPL/issues/4.

I plan to change the namespaces in nREPL in the next release as planned and I'm curious will you be OK to just cut a new release targeting the new nREPL, so I can open PRs for lein and boot as well.

**Comment by trptcolin** [comment]
👍 yeah that's fine.
