### ISSUE TITLE
What's the entry point of REPLy for nREPL

### ISSUE THREAD

**Issue by bbatsov** [trptcolin/reply#191]
I want to add some check for whether REPLy is present when starting nREPL via `clj`, but I'm not certain what exactly is its entry point for the connection and I assumed I could just ask here the wise and all-knowing @trptcolin. :-)

Basically I need something to call instead of https://github.com/nrepl/nREPL/blob/master/src/clojure/nrepl/cmdline.clj#L24, if `REPLy` is on the classpath.

**Comment by bbatsov** [comment]
To answer my own question - it seems I'm looking for https://github.com/trptcolin/reply/blob/master/src/clj/reply/eval_modes/nrepl.clj#L200 (or maybe `run-repl` in the same ns).

**Comment by trptcolin** [comment]
Not 100% sure on the use case, but you might want https://github.com/trptcolin/reply/blob/b70ee9fdd31a40be73b505f98cf38839d49b43e8/src/clj/reply/main.clj#L72-L79 or `-main` in that namespace - there's some added some stuff for signal handling (and also has the available options in that file). [Leiningen's repl task](https://github.com/technomancy/leiningen/blob/aba4502f59e30fd1e63c0530d8fc369683ae6c80/src/leiningen/repl.clj) or [Boot's repl task](https://github.com/boot-clj/boot/blob/7709941bcef20de55b940ec18885677df33b7557/boot/worker/src/boot/repl_client.clj) could be other good places to look for inspiration. Boot's definitely covers the basics, probably the best to start with?

**Comment by bbatsov** [comment]
I was looking at the Lein code, but your hint to check Boot was great! It's so much easier to get the basics now!
