### ISSUE TITLE
Travis builds failing for openjdk6 and oraclejdk7

### ISSUE THREAD

**Issue by mrichards42** [trptcolin/reply#196]
Builds are failing when trying to install these jvms: e.g. https://travis-ci.org/trptcolin/reply/jobs/489646637 and https://travis-ci.org/trptcolin/reply/jobs/489646639

According to [travis docs](https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images) it looks like these jvms are no longer installed by default.

**Comment by bbatsov** [comment]
Yeah. We should update the build matrix. Possible switch to Circle CI, given the news of Travis's demise.

**Comment by trptcolin** [comment]
Thanks, yep. I got the build green again, which should unblock PRs, but JDK6 is still missing for now so I'm leaving this open.

**Comment by bbatsov** [comment]
Do you think that running the build on JDK 6 and 7 is even needed at this point? According to the last Clojure survey it seems almost no one uses them. Probably focusing on Java 8, Java 11 and 12 (in general the supported LTS and short-cycle releases) is the best support strategy here.

**Comment by trptcolin** [comment]
My preference is always to maintain backwards compatibility / avoid breaking people. But if Leiningen's OK breaking support for JDK 6/7, then I'm OK with doing that in REPLy - as long as we bump major versions and make it really clear for users.

**Comment by bbatsov** [comment]
I share your sentiment in general, but I think that once we get to a point where almost no one is using something it becomes counter-productive to support it. I'm not sure what JDK Lein is targetting, but nREPL itself targets JDK 8 and so far no one was complained about this. Maybe it works on older the JDKs (I'm reasonably certain it works on 7), but we're not putting any efforts to ensure this.

**Comment by trptcolin** [comment]
Enabled! https://app.circleci.com/pipelines/github/trptcolin/reply

**Comment by bbatsov** [comment]
Thanks! 🙇

**Comment by bbatsov** [comment]
There's some weird failure as the OpenJDK has unexpected version format (there's a + there), but overall we're in business.
