### ISSUE TITLE
Jline error on blink-matching-paren

### ISSUE THREAD

**Issue by trptcolin** [trptcolin/reply#197]
See https://github.com/technomancy/leiningen/issues/2533 and https://github.com/jline/jline2/issues/298

**Comment by trptcolin** [comment]
If folks who are experiencing this can help verify that it's specifically *due to* the `blink-matching-paren` feature, that'll inform the fix.

Steps:
1. Validate the badness in the reply repo, via (`lein trampoline run`)
1. Change [this line](https://github.com/trptcolin/reply/blob/258eecedfd7f632434e37e8c258f78886a5c15ef/src/clj/reply/reader/simple_jline.clj#L97) to make `blink-parens false`
1. Validate whether that causes goodness in the reply repo (via `lein trampoline run`)

It seems like to make this configurable, this should default to the value in `$HOME/.inputrc` and `true` only if that's not present - that's where other config like this lives. Not sure why I didn't implement it that way - definitely a mistake.

**Comment by trptcolin** [comment]
FWIW I haven't been able to reproduce the issue on a VM with Ubuntu 18.04.2 / Leiningen 2.8.1 / OpenJDK 8 (1.8.0_191), so I'll definitely need help.

**Comment by trptcolin** [comment]
Per @bjaglin on upstream & downstream tickets (thanks!) this appears to be a bad kernel update. I'm looking for a non-Minecraft-forum source for this, but... Wowsers!

**Comment by trptcolin** [comment]
Ah, here's the official stuff: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1813873

**Comment by bbatsov** [comment]
Wow! This doesn't happen every day!

**Comment by trptcolin** [comment]
Calling this closed - workaround is to upgrade/downgrade kernel to *not* be Ubuntu `4.15.0-44` or `4.15.0-45`.
