### ISSUE TITLE
Initialization code breaks `incomplete.core/resolve-class`

### ISSUE THREAD

**Issue by hsartoris-bard** [trptcolin/reply#205]
It looks like some legacy code was ported over, as the following lines were present before the move to incomplete, merely modified: 

https://github.com/trptcolin/reply/blob/9698d40ca2be8b4b93108e92d3698ef37570d001/src/clj/reply/initialization.clj#L152-L155

In any case, this is strictly nonfunctional as there is a guaranteed arity mismatch. Removing the entire function with `with-redefs` works, and, given that incomplete is a dependency that gets required where it seems to be needed, I'm not sure that this function as a whole is necessary. It seems to enable a development workflow that's no longer needed with lein checkouts and `:deps/root`.

**Comment by bbatsov** [comment]
I've just noticed the bug as well and I wondering how to best approach it, as I can't find any usages of the `resolve-class` that gets exported here. I can tweak the arity in incomplete as quick fix (the version there takes a `ns` and a `sym`, the old version took only a `sym`, but it'd be nice if we just removed the code if it's truly redundant. @trptcolin Any thoughts?
